apiVersion: apps/v1
kind: Deployment
metadata:
  name: tyud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tyud
  template:
    metadata:
      labels:
        app: tyud
    spec:
      containers:
      - image: okteto.dev/tyud:latest
        name: tyud
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "7c904a70-d608-4534-a8db-72ed2bc43f99"
        - name: Vless_Path
          value: "/vl5bthyuagh55"
        - name: Vmess_UUID
          value: "7c904a70-d608-4534-a8db-72ed2bc43f99"
        - name: Vmess_Path
          value: "/vm6ndysh6yj66"
        - name: Share_Path
          value: "/v2link"
